"use client";
import Footer from "@/components/Footer";
import "./globals.css";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "@/components/Header/NavbarItems";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";
import Splash from "../components/SplashScreen/Splash";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const pathname = usePathname();
  const isHome = pathname === "/";
  const [isLoading, setIsLoading] = useState(isHome);

  useEffect(() => {
    if (isLoading) return;
  }, [isLoading]);
  return (
    <html lang="en">
      <body className={inter.className}>
        {isLoading && isHome ? (
          <Splash finishLoading={() => setIsLoading(false)} />
        ) : (
          <>
            <Header /> <ToastContainer />
            {children}
            <Footer />
          </>
        )}
      </body>
    </html>
  );
}
